version: '3.8'

services:
  app:
    build: .
    command: gunicorn -b 0.0.0.0:5000 r_app:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A r_app.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
